name: .NET Core CI/CD with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: [ self-hosted, Linux, X64 ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        ref: 'master'
